# Database Component 
dsas_db_vol_container:
   image: alpine
   volumes:
       - /var/lib/postgresql
   command: /bin/echo "Data only container for DSAS PostGRES"
   labels:
     - "gov.usgs.cidsa.dsas.container.volume=true"
dsas_db:
  extends:
    file: ./dsas-liquibase/docker-compose.yml
    service: db
  volumes_from: 
    - dsas_db_vol_container

# Geoserver
dsas_geoserver_vol_container:
    image: alpine
    volumes:
        - /heapdumps
        - /data
    command: /bin/echo "Data only container for Geoserver"
    labels:
      - "gov.usgs.cidsa.dsas.container.volume=true"
dsas_geoserver:
  extends:
    file: ./dsas-geoserver/docker-compose.yml
    service: dsas_geoserver
  volumes_from:
    - dsas_geoserver_vol_container
  links:
    - dsas_db

# RServe
dsas_rserve:
  extends:
    file: ./dsas-n52/docker-compose.yml
    service: dsas_rserve

# N52
dsas_52n:
  extends:
    file: ./dsas-n52/docker-compose.yml
    service: dsas_n52
  links:
    - dsas_rserve

    
# UI
dsas_ui:
  extends:
    file: ./dsas-web-ui/docker-compose.yml
    service: dsas_ui
  volumes_from:
    - dsas_geoserver_vol_container
  links:
    - dsas_db
    - dsas_geoserver
    - dsas_52n