# Database Component 
# Set the environment SKIP_LIQUIBASE to a non-empty value to skip running 
# liquibase when container starts. 
dsas_db_vol_container:
    image: alpine
    volumes:
      - /var/lib/postgresql
    command: /bin/echo "Data only container for DSAS PostGRES"
    labels:
      - "gov.usgs.cidsa.dsas.container.volume=true"
    container_name: DSAS_Database_Volume
dsas_db:
  extends:
    file: ./dsas-liquibase/docker-compose.yml
    service: db
  volumes_from: 
    - dsas_db_vol_container
  container_name: DSAS_Database
#  environment:
#   - SKIP_LIQUIBASE=true

# Geoserver
dsas_geoserver_vol_container:
    image: alpine
    volumes:
        - /heapdumps
        - /data
    command: /bin/echo "Data only container for Geoserver"
    labels:
      - "gov.usgs.cidsa.dsas.container.volume=true"
    container_name: DSAS_Geoserver_Volume
dsas_geoserver:
  extends:
    file: ./geoserver/dsas-geoserver/docker-compose.yml
    service: dsas_geoserver
  volumes_from:
    - dsas_geoserver_vol_container
  links:
    - dsas_db
  container_name: DSAS_Geoserver

# RServe
dsas_rserve:
  extends:
    file: ./dsas-n52/docker-compose.yml
    service: dsas_rserve
  container_name: DSAS_RServe

# N52
dsas_52n:
  extends:
    file: ./dsas-n52/docker-compose.yml
    service: dsas_n52
  links:
    - dsas_rserve
  container_name: DSAS_52N

    
# UI
dsas_ui:
  extends:
    file: ./dsas-web-ui/docker-compose.yml
    service: dsas_ui
  volumes_from:
    - dsas_geoserver_vol_container
  links:
    - dsas_db
    - dsas_geoserver
    - dsas_52n
  container_name: DSAS_UI